### ISSUE TITLE
When I run the code, there are some problems when loading epigenomic data (CTCF) and store into arrays 

### ISSUE THREAD

**Issue by HappyLife-together** [liu-bioinfo-lab/caesar#3]
run 01_generate_example_input_regions.py

Step 2: Load epigenomic data and store into arrays
  DNase_seq
  CTCF
Traceback (most recent call last):
  File "01_generate_example_input_regions.py", line 221, in <module>
    epigenomic2array(bigwig_path, epi_names, [i for i in ch_coord.keys()], epi_folder)
  File "01_generate_example_input_regions.py", line 157, in epigenomic2array
    load_bigWig_for_entire_genome(f'{input_path}.bigWig', epi_name, chroms, epi_path=ouput_folder)
  File "01_generate_example_input_regions.py", line 112, in load_bigWig_for_entire_genome
    vec = bw.stats(ch, 0, end_pos, exact=True, nBins=nBins)
RuntimeError: Invalid interval bounds!

**Comment by dmcbffeng** [comment]
Thank you for the feedback!
Actually, we used bedGraph in our runs. When uploading the data for sharing, we used the original bigWig data to minimize the storage space. But it seems pyBigWig will raise some issues when the boundary exceeds the chrom size.

Now we re-upload the bedGraph files and removed the bigWig files. You could download them from the same DropBox link and it should work this time.
